# Generated by Django 4.2.8 on 2024-01-08 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_paperinfo_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paperinfo',
            name='column',
        ),
        migrations.AddField(
            model_name='paperinfo',
            name='paper_author',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
