# Generated by Django 4.2.8 on 2024-01-08 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_delete_papercolumn_alter_paperinfo_paper_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperinfo',
            name='reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='paperinfo',
            name='author',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
