# Generated by Django 4.2.8 on 2024-01-11 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_paperinfo_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paperinfo',
            name='pdf_file',
            field=models.FileField(blank=True, upload_to='pdfFiles/'),
        ),
    ]
